---
namespace: community
name: odoo-role
version: 1.0.0
readme: README.md
authors:
  - Daniel JOSEPH
description: Installation de postgres et odoo
license_file: BSD
tags:
  - v1
repository: https://github.com/lianhuahayu/odoo_role.git
documentation: https://github.com/lianhuahayu/odoo_role.git
homepage: https://github.com/lianhuahayu/odoo_role.git
issues: https://github.com/lianhuahayu/odoo_role.git
build_ignore:
  - .gitignore
 